### ISSUE TITLE
Stitcher crash - release-2.5

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#548] opened 2015-05-18 22:33 UTC
I was trying something (admitidly non-standard) today with stitcher
(gcf branch  release-2.5) and after all the slivers where created stitcher crashed. 
Tracebakc:
```
09:15:03 INFO     stitch.launcher: All aggregates are complete.
Traceback (most recent call last):
  File "/home/nriga/gcf/src/stitcher.py", line 199, in <module>
    sys.exit(main())
  File "/home/nriga/gcf/src/stitcher.py", line 180, in main
    text, item = call(argv)
  File "/home/nriga/gcf/src/stitcher.py", line 171, in call
    return handler.doStitching(args)
  File "/home/nriga/gcf/src/gcf/omnilib/stitchhandler.py", line 214, in doStitching
    combinedManifest = self.combineManifests(self.ams_to_process, lastAM)
  File "/home/nriga/gcf/src/gcf/omnilib/stitchhandler.py", line 1254, in combineManifests
    manString = combinedManifestDom.toprettyxml(encoding="utf-8")
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 57, in toprettyxml
    self.writexml(writer, "", indent, newl, encoding)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 1749, in writexml
    node.writexml(writer, indent, addindent, newl)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 817, in writexml
    node.writexml(writer,indent+addindent,addindent,newl)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 817, in writexml
    node.writexml(writer,indent+addindent,addindent,newl)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 812, in writexml
    _write_data(writer, attrs[a_name].value)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 301, in _write_data
    data = data.replace("&", "&amp;").replace("<", "&lt;")
AttributeError: 'NoneType' object has no attribute 'replace'
```

 _Imported from trac ticket [#548](http://trac.gpolab.bbn.com/gcf/ticket/548),  created by nriga on 03-05-2014 at 09:24, last modified: 03-05-2014 at 14:58_

**Comment by innnkkki** [comment] 2015-05-18 22:33
_nriga (innnkkki) attached [excl-of-stitching.xml](http://trac.gpolab.bbn.com/gcf/attachment/ticket/548/excl-of-stitching.xml) on 03-05-2014 at 09:24_

**Comment by innnkkki** [comment] 2015-05-18 22:34
_nriga (innnkkki) attached [testexp-manifest-rspecs.tar.gz](http://trac.gpolab.bbn.com/gcf/attachment/ticket/548/testexp-manifest-rspecs.tar.gz) on 03-05-2014 at 11:43_

**Comment by ahelsing** [comment] 2015-05-18 22:34
I haven't been able to reproduce this.

_Trac comment by ahelsing on 03-05-2014 at 10:38_

**Comment by ahelsing** [comment] 2015-05-18 22:34
Conceivably this is related to http://groups.geni.net/geni/ticket/1200, but as I say I couldn't reproduce the problem.

_Trac comment by ahelsing on 03-05-2014 at 10:49_

**Comment by ahelsing** [comment] 2015-05-18 22:34
The stacktrace indicates that the value for some attribute was a python `None` - but somewhere deep inside the DOM. So unless the manifest combiner adds an attribute with a value of none, I'm not sure what stitcher can do here.

_Trac comment by ahelsing on 03-05-2014 at 11:26_

**Comment by innnkkki** [comment] 2015-05-18 22:34
I am attaching all the manifests. I am trying to reproduce this now and let you know if it was a one off. 



_Trac comment by nriga (github user: innnkkki) on 03-05-2014 at 11:44_

**Comment by innnkkki** [comment] 2015-05-18 22:34
I can concistently reproduce it with the rspec I attached this morning, again non-standard:-)

_Trac comment by nriga (github user: innnkkki) on 03-05-2014 at 11:47_

**Comment by ahelsing** [comment] 2015-05-18 22:34
And I still can't.

Can you run it with --debug and send me the logs?

My best guess at the moment is that this is indeed related to the ION AM bug I listed earlier. The ION AM manifest you show lists an empty 'xmlns' attribute on the emulab:openflow_controller attribute.

_Trac comment by ahelsing on 03-05-2014 at 12:11_

**Comment by ahelsing** [comment] 2015-05-18 22:34
I've decided this is a duplicate of ticket #549. Which I've now fixed.

_Trac comment by ahelsing on 03-05-2014 at 14:58_

**Closed** 2015-05-18 22:34 UTC
Labels: duplicate, stitcher, task
