### ISSUE TITLE
Omni: add remote-execute.py to the MAC release

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#620] opened 2015-05-18 23:08 UTC
The click router tutorial, requires the remote-execute script. We should make a MAC executable and include it in the next release. 

Note: This is not easily supported in Windows (requires OpenSSH) so we will not include it there. 

 _Imported from trac ticket [#620](http://trac.gpolab.bbn.com/gcf/ticket/620),  created by nriga on 05-29-2014 at 10:26, last modified: 05-30-2014 at 09:19_

**Comment by ahelsing** [comment] 2015-05-18 23:08
duplicate of #601

_Trac comment by ahelsing on 05-30-2014 at 09:19_

**Closed by ahelsing** 2015-05-18 23:08 UTC
Labels: duplicate, omni, task
