### ISSUE TITLE
readyToLogin.py reports exception when executed immediately after createsliver

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#399] opened 2015-05-18 20:07 UTC
While running a test, issued a readyToLogin.py immediately after the sliver creation.  This caused an exception captured below. Note that subsequent readyToLogin.py was successful:
```

$ readyToLogin.py -a missouri-ig IG-CT-4
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.4.1/examples/readyToLogin.py", line 846, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.4.1/examples/readyToLogin.py", line 833, in main
    loginInfoDict, keyList = main_no_print(argv=argv)
  File "/home/lnevers/gcf-2.4.1/examples/readyToLogin.py", line 821, in main_no_print
    amLoginInfo = addNodeStatus(amUrl, amType, amLoginInfo)
  File "/home/lnevers/gcf-2.4.1/examples/readyToLogin.py", line 463, in addNodeStatus
    amLoginInfo = addNodeStatusPG( amLoginInfo, amSliverStat )
  File "/home/lnevers/gcf-2.4.1/examples/readyToLogin.py", line 473, in addNodeStatusPG
    for resourceDict in amSliverStat['geni_resources']:
TypeError: 'bool' object is unsubscriptable

$ readyToLogin.py -a missouri-ig IG-CT-4
#========================================
#SSH CONFIGURATION INFO for User lnevers
#========================================
 
Host missouri-ig
  Port 32314
  HostName pc1.instageni.rnet.missouri.edu
  User lnevers 
  IdentityFile /home/lnevers/.ssh/geni_cert_portal_key 
 
Host missouri-ig2
  Port 32315
  HostName pc1.instageni.rnet.missouri.edu
  User lnevers 
  IdentityFile /home/lnevers/.ssh/geni_cert_portal_key 

================================================================================
LOGIN INFO for AM: https://instageni.rnet.missouri.edu:12369/protogeni/xmlrpc/am
================================================================================

For more login info, see the section entitled:
	 'Providing a private key to ssh' in 'readyToLogin.py -h'

missouri-ig2's geni_status is: changing (am_status:changing) 
User lnevers logs in to missouri-ig2 using:
	ssh -p 32315  -i /home/lnevers/.ssh/geni_cert_portal_key lnevers@pc1.instageni.rnet.missouri.edu

missouri-ig's geni_status is: changing (am_status:changing) 
User lnevers logs in to missouri-ig using:
	ssh -p 32314  -i /home/lnevers/.ssh/geni_cert_portal_key lnevers@pc1.instageni.rnet.missouri.edu

NOTE: If your user is not listed, try using the --no-keys option.
```

Will work on reproducing the problem, but the window when this happens is a few seconds. 

Using version gcf 2.4.1, which is not available from the "Version" pull-down.

 _Imported from trac ticket [#399](http://trac.gpolab.bbn.com/gcf/ticket/399),  created by lnevers on 10-11-2013 at 11:54, last modified: 02-24-2014 at 20:21_

**Comment by ahelsing** [comment] 2015-05-18 20:08
Probably sliverstatus returned false - cause the server was essentially giving an error.

_Trac comment by ahelsing on 10-11-2013 at 12:11_

**Comment by seledwards** [comment] 2015-05-18 20:08
Assigning to 2.5.  We should fix this for the next release to print a more friendly explanation.

_Trac comment by sedwards (github user: seledwards) on 10-11-2013 at 12:44_

**Comment by seledwards** [comment] 2015-05-18 20:08
I put in some code that looks like it fixed this.  I tried three times to reproduce the error and couldn't. Closing.

_Trac comment by sedwards (github user: seledwards) on 02-24-2014 at 20:21_

**Closed by seledwards** 2015-05-18 20:08 UTC
Labels: omni
